# Generated by Django 4.2.27 on 2026-01-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("job_title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("linkedin_profile", models.URLField(blank=True, null=True)),
                ("resume_link", models.URLField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
