# Generated by Django 4.2.27 on 2026-01-11 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("posted_date", models.DateField(default=datetime.date.today)),
                ("deadline", models.DateField()),
                (
                    "tags",
                    models.TextField(
                        help_text="Comma-separated tags e.g. 'Java, Spring Boot'"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full-Time"),
                            ("Internship", "Internship"),
                            ("Off-Campus Drive", "Off-Campus Drive"),
                            ("Hiring Challenge", "Hiring Challenge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("batch_year", models.CharField(max_length=50)),
                (
                    "logo_url",
                    models.URLField(
                        default="https://cdn-icons-png.flaticon.com/512/732/732221.png"
                    ),
                ),
                ("apply_link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
