# Generated by Django 4.2.27 on 2026-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerform", "0002_jobposting"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="experience",
            field=models.CharField(default="Fresher", max_length=100),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="batch_year",
            field=models.CharField(max_length=100),
        ),
    ]
