# Generated by Django 4.2.27 on 2026-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerform", "0003_jobposting_experience_alter_jobposting_batch_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
