# Generated by Django 4.2.27 on 2026-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerform", "0004_alter_jobposting_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="batch_year",
            field=models.CharField(
                help_text="Comma separated years e.g. '2022, 2023'", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="deadline",
            field=models.DateField(default="Fresher"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="tags",
            field=models.TextField(
                help_text="Comma-separated tags e.g. 'Python, SQL, AI/ML'"
            ),
        ),
    ]
