# Generated by Django 4.2.27 on 2026-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careerform", "0005_alter_jobposting_batch_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="salary_range",
            field=models.CharField(
                blank=True, help_text="e.g. 5-8 LPA", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="batch_year",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="tags",
            field=models.TextField(
                help_text="Comma-separated tags e.g. 'Java, Spring Boot'"
            ),
        ),
    ]
