# Generated by Django 4.2.27 on 2026-01-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "careerform",
            "0006_jobposting_salary_range_alter_jobposting_batch_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
