# Generated by Django 4.2.27 on 2026-01-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signin", "0004_remove_signinprofile_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="signinprofile",
            name="availability",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="company",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="current_year",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="linkedin_profile",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="looking_for_internship",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="referral_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="signinprofile",
            name="resume_link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="signinprofile",
            name="years_of_experience",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
