# Generated by Django 4.2.27 on 2026-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signin", "0005_signinprofile_availability_signinprofile_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signinprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
