# Generated by Django 4.2.27 on 2026-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signin", "0006_alter_signinprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signinprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
