# Generated by Django 4.2.27 on 2026-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("template_id", models.CharField(max_length=100)),
                (
                    "template_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
